version: '3.3'

services:
  web:
    build: ..
    command: gunicorn -w 4 -b 0.0.0.0:5000 webappPOC_2:app
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev